FROM nginx:alpine

# Создаем директории для логов
RUN mkdir -p /var/log/nginx

# Создаем директории для статических файлов
RUN mkdir -p /var/www/static /var/www/media

# Устанавливаем права
RUN chown -R nginx:nginx /var/log/nginx /var/www

# Копируем конфигурацию
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]